In [1]:
import pandas as pd

In [2]:
file_name = 'model 1 en 6 marginale kosten_breed.xlsx'
xls = pd.ExcelFile(file_name)
xls.sheet_names

['M1_TotaleZorgkosten',
 'M1_nopzvwkhuisartsconsult',
 'M1_GGZkosten',
 'M1_zvwkfarmacie',
 'M1_zvwkziekenhuis',
 'M6_TotaleZorgkosten',
 'M6_nopzvwkhuisartsconsult',
 'M6_GGZkosten',
 'M6_zvwkfarmacie',
 'M6_zvwkziekenhuis']

In [3]:
# start with first sheet
sheet_name = xls.sheet_names[0]
first_underscore = sheet_name.find('_')
model = sheet_name[:first_underscore]
uitkomstmaat = sheet_name[first_underscore+1:]

results = (pd.read_excel(file_name, sheet_name)
          .rename(columns={'Unnamed: 0': 'ggd_regio'})
          .set_index('ggd_regio')
          .T)
results['model'] = model
results['uitkomstmaat'] = uitkomstmaat
results['type_uitkomstmaat'] = 'Kosten'
if uitkomstmaat in ['Alg_gez_0goed_1slecht', 'Chron_ziekte_0_nee', 'Hoog_Risico_Depr']:
    results['type_uitkomstmaat'] = 'Gezondheid'

# en dan plakken we de rest erachter
for sheet_name in xls.sheet_names[1:]:
    first_underscore = sheet_name.find('_')
    model = sheet_name[:first_underscore]
    uitkomstmaat = sheet_name[first_underscore+1:]
    
    df = (pd.read_excel(file_name, sheet_name)
              .rename(columns={'Unnamed: 0': 'ggd_regio'})
              .set_index('ggd_regio')
              .T)
    df['model'] = model
    df['uitkomstmaat'] = uitkomstmaat
    df['type_uitkomstmaat'] = 'Kosten'
    if uitkomstmaat in ['Alg_gez_0goed_1slecht', 'Chron_ziekte_0_nee', 'Hoog_Risico_Depr']:
        df['type_uitkomstmaat'] = 'Gezondheid'
        
    results = pd.concat([results, df], axis=0)

results.index.name = 'ggd_regio'
results

ggd_regio,b,se,t,pvalue,ll,ul,model,uitkomstmaat,type_uitkomstmaat
ggd_regio,,,,,,,,,
GGD Groningen,2200.809,7474382.0,29.44,0.0,2054.313,2347.304,M1,TotaleZorgkosten,Kosten
GGD Fryslan,2286.235,7829961.0,29.20,0.0,2132.770,2439.700,M1,TotaleZorgkosten,Kosten
GGD Drenthe,2308.475,1159627.0,19.91,0.0,2081.192,2535.759,M1,TotaleZorgkosten,Kosten
GGD IJsselland,2271.218,8129178.0,27.94,0.0,2111.888,2430.548,M1,TotaleZorgkosten,Kosten
GGD Twente,2415.586,1265318.0,19.09,0.0,2167.587,2663.584,M1,TotaleZorgkosten,Kosten
...,...,...,...,...,...,...,...,...,...
GGD Hart voor Brabant,1332.290,1095942.0,12.16,0.0,1117.489,1547.091,M6,zvwkziekenhuis,Kosten
GGD Brabant Zuidoost,1264.032,4060206.0,31.13,0.0,1184.453,1343.611,M6,zvwkziekenhuis,Kosten
GGD Limburg-Noord,1328.700,7321909.0,18.15,0.0,1185.192,1472.207,M6,zvwkziekenhuis,Kosten
GGD Zuid-Limburg,1256.559,3182899.0,39.48,0.0,1194.175,1318.942,M6,zvwkziekenhuis,Kosten
GGD Flevoland,1216.960,8500657.0,14.32,0.0,1050.349,1383.570,M6,zvwkziekenhuis,Kosten

In [4]:
results.to_csv('modeluitkomsten_voor_tool.csv')

In [5]:
results.index.name

'ggd_regio'