In [2]:
import numpy as np
import pandas as pd

In [12]:
np.random.seed(42)

models = range(1,7)
ggd_regios = [f'GGD regio {i}' for i in range(1, 26)]
uitkomstmaten = ['Gezondheid Algemeen',
               'Totale Zorgkosten']

df = pd.DataFrame(columns=['uitkomstmaat', 'model', 'ggd_regio', 'b', 'll', 'ul'])

for maat in uitkomstmaten:
    for model in models:

        # voor gezondheidsmaten zijn beta's als probabilities
        beta = np.random.normal(.4, .1, size=25)
        # bij model 3 en later zijn de probabilities van regio's minder verschillend
        if 'gezondheid' in maat.lower() and model >= 3:
            beta = np.random.normal(.24, .01, size=25)
            
        # voor kosten uitkomstmaten zijn beta's als marginale kosten in euro's
        if 'kosten' in maat.lower():
            beta = np.random.normal(2200, 250, size=25)
            if model >= 3:
                beta = np.random.normal(2200, 50, size=25)
        
        se = beta * np.random.normal(0.05, 0.01)
        
        lower_limit = beta - 1.96 * se
        upper_limit = beta + 1.96 * se
        
        model_df = pd.DataFrame({'uitkomstmaat': [maat] * 25,
                                'model': [model] * 25,
                                'ggd_regio': ggd_regios,
                                'b': beta,
                                'll': lower_limit,
                                'ul': upper_limit})
        
        df = pd.concat([df, model_df], axis=0)

df

,uitkomstmaat,model,ggd_regio,b,ll,ul
0,Gezondheid Algemeen,1,GGD regio 1,0.449671,0.404626,0.494717
1,Gezondheid Algemeen,1,GGD regio 2,0.386174,0.347489,0.424858
2,Gezondheid Algemeen,1,GGD regio 3,0.464769,0.418211,0.511327
3,Gezondheid Algemeen,1,GGD regio 4,0.552303,0.496977,0.607629
4,Gezondheid Algemeen,1,GGD regio 5,0.376585,0.338861,0.414309
...,...,...,...,...,...,...
20,Totale Zorgkosten,6,GGD regio 21,2200.696465,2008.616234,2392.776696
21,Totale Zorgkosten,6,GGD regio 22,2198.793746,2006.879587,2390.707904
22,Totale Zorgkosten,6,GGD regio 23,2209.904238,2017.020338,2402.788138
23,Totale Zorgkosten,6,GGD regio 24,2192.781979,2001.392537,2384.171422
24,Totale Zorgkosten,6,GGD regio 25,2171.316900,1981.800963,2360.832836

In [ ]:
# dat is het begin, maar dan moet er nog per regio bekeken worden welke andere regio's significant verschillen door de lower en upper limits te vergelijken


# per maat
# per model
# per regio:
    # maak een kopie van df met deze maat en model:
    # voeg de kolommen 'ref-regio', 'p-waarde' en 'verschil' toe. En evt lower_limit_ref_regio en upper_limit_ref_regio
        # wanneer de upper_limit van andere regio lager ligt dan lower limit van de ref-regio:
            # dan is die andere regio significant goedkoper
            # noteer significantie ja/nee (kolom 'p-waarde')
            # noteer verschil in % of EUR (kolom 'verschil')
        # wanneer de lower_limit van andere regio hoger ligt dan de upper_limit van de ref-regio:
            # dan is die andere regio significant duurder
            # noteer significantie ja/nee (kolom 'p-waarde')
            # noteer verschil in % of EUR (kolom 'verschil')
    # voeg de kopie toe aan nieuwe (hele lange) tabel